### ISSUE TITLE
模块编译依赖的Node版本过低，使用electron-rebuild无法重新编译该模块

### ISSUE THREAD

**Issue by maskerliu** [zegoim/zego-electron-quick-start#1]
Uncaught Error: The module '/zego-electron-quick-start-master/node_modules/zegoliveroom/ZegoLiveRoom.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by xuhongming251** [comment]
目前需要提供node版本号和electron版本号：
通过node -v 查看版本号。

然后zego提供服务帮助编译相关版本号的库并上传。

**Comment by maskerliu** [comment]
node 11.6.0 electron 4.1.5, thx

**Comment by xuhongming251** [comment]
[190510_141149_heads_master-0-g63c963f_node_v11.6.0_electron_v4.1.5_win.zip](https://github.com/zegoim/zego-electron-quick-start/files/3165107/190510_141149_heads_master-0-g63c963f_node_v11.6.0_electron_v4.1.5_win.zip)

@maskerliu

**Comment by maskerliu** [comment]
好效率，👍👍👍

**Comment by maskerliu** [comment]
麻烦也提供一下mac版本的哈

**Comment by xuhongming251** [comment]
[190510_171222_heads_master-0-g5c5ed3c_node_v11.6.0_electron_v4.1.5_x64_mac.zip](https://github.com/zegoim/zego-electron-quick-start/files/3165755/190510_171222_heads_master-0-g5c5ed3c_node_v11.6.0_electron_v4.1.5_x64_mac.zip)

@maskerliu

**Comment by xuhongming251** [comment]
已提供上传。




------------------ 原始邮件 ------------------
发件人: "maskerliu"<notifications@github.com>; 
发送时间: 2019年5月10日(星期五) 下午4:32
收件人: "zegoim/zego-electron-quick-start"<zego-electron-quick-start@noreply.github.com>; 
抄送: "小豹~"<494462498@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zegoim/zego-electron-quick-start] 模块编译依赖的Node版本过低，使用electron-rebuild无法重新编译该模块 (#1)




麻烦也提供一下mac版本的哈

**Comment by maskerliu** [comment]
给力

**Comment by TheHtmler** [comment]
node v10.22.1 electron 5.0.8 mac, 同样的错误，上面的包能用吗
