### ISSUE TITLE
electron-vue脚手架下引用，调用loginRoom返回的房间流信息中总会随机出现错误流信息

### ISSUE THREAD

**Issue by maskerliu** [zegoim/zego-electron-quick-start#3]
electron-vue脚手架下引用，调用loginRoom返回的房间流信息中总会随机出现错误流信息

stream_list: Array(3)
0: {stream_id: "7fea4ce8a6ba4141927ec09164efd44544333343", user_name: "", user_id: "7fea4ce8a6ba4141927ec09164efd445", extra_info: ""}
1: {stream_id: "", user_name: "", user_id: "", extra_info: "b1df6583c136b4e4d019dd143c27db06"}
2: {stream_id: "��", user_name: "", user_id: "", extra_info: ""}
length: 3

类似以上

**Comment by xuhongming251** [comment]
我们这边测试的没有发现这个问题，你那边方便取一下日志吗。

在 我的电脑 路径下直接输入 %APPDATA% 找到带有.ZEGO.SDK的文件夹。
把目录里的日志文件发过来看下什么原因。
zegoavlog1.txt

**Comment by maskerliu** [comment]
我在mac下运行，相关的路径是什么呢

**Comment by maskerliu** [comment]
或者您这边联系方式方便给我一个，我跟您请假一下哈

**Comment by xuhongming251** [comment]
你先加我QQ，494462498
